allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': false
  '@google/genai': false
  esbuild: true
  koffi: false
  node-pty: false
  protobufjs: false

peerDependencyRules:
  allowedVersions:
    react: '>=16.8 <20'
